const itemIndex = {
    "Dirt": "images/dirt.png",
    "Stone": "images/stone.png",
    "Stone Wall": "images/stone_wall.png",
    "Sand": "images/sand.png",
    "Lava": "images/lava.png",
    "Obsidian": "images/obsidian.png",
    "Marble": "images/marble.png",
    "Water": "images/water.png",
    "Grass": "images/grass.png",
    "Mud": "images/mud.png",
    "Soil": "images/soil.png",
    "Bush": "images/bush.png",
    "Tree": "images/tree.png",
    "Wood Block": "images/wood_block.png",
    "Rose": "images/rose.png",
    "Sunflower": "images/sunflower.png",
    "Cactus": "images/cactus.png",
    "Bricks": "images/bricks.png",
    "Well": "images/well.png",
    "Red Block": "images/red_block.png",
    "Green Block": "images/green_block.png",
    "Blue Block": "images/blue_block.png",
    "Yellow Block": "images/yellow_block.png",
    "Orange Block": "images/orange_block.png",
    "Forge": "images/forge.png",
    "Mushroom": "images/mushroom.png",
    "Glass Block": "images/glass_block.png",
    "Pinball Sproinger": "images/pinball_sproinger.png",
    "White Block": "images/white_block.png",
    "Black Block": "images/black_block.png",
    "Clay": "images/clay.png",
    "Toilet": "images/toilet.png",
    "Wooden Chair": "images/wooden_chair.png",
    "Bed": "images/bed.png",
    "Andesite": "images/andesite.png",
    "Granite": "images/granite.png",
    "Door": "images/door.png",
    "Dungeon Door": "images/dungeon_door.png",
    "Sign": "images/sign.png",
    "Danger Sign": "images/danger_sign.png",
    "Death Spikes": "images/death_spikes.png",
    "Portcullis": "images/portcullis.png",
    "Steel Block": "images/steel_block.png",
    "Bedrock": "images/bedrock.png",
    "White Wallpaper": "images/white_wallpaper.png",
    "Black Wallpaper": "images/black_wallpaper.png",
    "Red Wallpaper": "images/red_wallpaper.png",
    "Green Wallpaper": "images/green_wallpaper.png",
    "Blue Wallpaper": "images/blue_wallpaper.png",
    "Yellow Wallpaper": "images/yellow_wallpaper.png",
    "Orange Wallpaper": "images/orange_wallpaper.png",
    "Carnival Wallpaper": "images/carnival_wallpaper.png",
    "Broccoli": "images/broccoli.png",
    "Carnival Pinwheel": "images/carnival_pinwheel.png",
    "Carnival Spikeball": "images/carnival_spikeball.png",
    "Golden Block": "images/golden_block.png",
    "Industrial Fan": "images/industrial_fan.png",
    "Ceiling Fan": "images/ceiling_fan.png",
    "Clouds": "images/clouds.png",
    "Checker Wallpaper": "images/checker_wallpaper.png",
    "Tomato": "images/tomato.png",
    "Egg": "images/egg.png",
    "Wheat": "images/wheat.png",
    "Dough": "images/dough.png",
    "Bread": "images/bread.png",
    "Stove": "images/stove.png",
    "Apron": "images/apron.png",
    "Spatula": "images/spatula.png",
    "Chef Hat": "images/chef_hat.png",
    "Carrot Block": "images/carrot_block.png",
    "Strawberry Block": "images/strawberry_block.png",
    "Polka Dot Block": "images/polka_dot_block.png",
    "Picket Fence": "images/picket_fence.png",
    "Traffic Barricade": "images/traffic_barricade.png",
    "Street Sign": "images/street_sign.png",
    "Open Sign": "images/open_sign.png",
    "Holographic Sign": "images/holographic_sign.png",
    "Straw Hat": "images/straw_hat.png",
    "Cheeseburger": "images/cheeseburger.png",
    "Wooden Background": "images/wooden_background.png",
    "Lattice Background": "images/lattice_background.png",
};
