const itemIndex = {
    "Dirt": { image: "images/dirt.png", tier: 1 },
    "Stone": { image: "images/stone.png", tier: 1 },
    "Stone Wall": { image: "images/stone_wall.png", tier: 2 },
    "Sand": { image: "images/sand.png", tier: 1 },
    "Lava": { image: "images/lava.png", tier: 1 },
    "Obsidian": { image: "images/obsidian.png", tier: 2 },
    "Marble": { image: "images/marble.png", tier: 1 },
    "Water": { image: "images/water.png", tier: 1 },
    "Grass": { image: "images/grass.png", tier: 1 },
    "Mud": { image: "images/mud.png", tier: 2 },
    "Bush": { image: "images/bush.png", tier: 2 },
    "Tree": { image: "images/tree.png", tier: 3 },
    "Wood Block": { image: "images/wood_block.png", tier: 4 },
    "Rose": { image: "images/rose.png", tier: 3 },
    "Sunflower": { image: "images/sunflower.png", tier: 4 },
    "Cactus": { image: "images/cactus.png", tier: 4 },
    "Bricks": { image: "images/bricks.png", tier: 5 },
    "Well": { image: "images/well.png", tier: 3 },
    "Red Block": { image: "images/red_block.png", tier: 5 },
    "Green Block": { image: "images/green_block.png", tier: 5 },
    "Blue Block": { image: "images/blue_block.png", tier: 5 },
    "Yellow Block": { image: "images/yellow_block.png", tier: 5 },
    "Orange Block": { image: "images/orange_block.png", tier: 6 },
    "Forge": { image: "images/forge.png", tier: 4 },
    "Mushroom": { image: "images/mushroom.png", tier: 3 },
    "Glass Block": { image: "images/glass_block.png", tier: 5 },
    "Pinball Sproinger": { image: "images/pinball_sproinger.png", tier: 6 },
    "White Block": { image: "images/white_block.png", tier: 5 },
    "Black Block": { image: "images/black_block.png", tier: 5 },
    "Clay": { image: "images/clay.png", tier: 4 },
    "Toilet": { image: "images/toilet.png", tier: 6 },
    "Wooden Chair": { image: "images/wooden_chair.png", tier: 7 },
    "Bed": { image: "images/bed.png", tier: 8 },
    "Andesite": { image: "images/andesite.png", tier: 2 },
    "Granite": { image: "images/granite.png", tier: 3 },
    "Door": { image: "images/door.png", tier: 5 },
    "Dungeon Door": { image: "images/dungeon_door.png", tier: 6 },
    "Sign": { image: "images/sign.png", tier: 5 },
    "Danger Sign": { image: "images/danger_sign.png", tier: 6 },
    "Death Spikes": { image: "images/death_spikes.png", tier: 7 },
    "Portcullis": { image: "images/portcullis.png", tier: 8 },
    "Steel Block": { image: "images/steel_block.png", tier: 9 },
    "Bedrock": { image: "images/bedrock.png", tier: 10 },
    "White Wallpaper": { image: "images/white_wallpaper.png", tier: 6 },
    "Black Wallpaper": { image: "images/black_wallpaper.png", tier: 6 },
    "Red Wallpaper": { image: "images/red_wallpaper.png", tier: 6 },
    "Green Wallpaper": { image: "images/green_wallpaper.png", tier: 6 },
    "Blue Wallpaper": { image: "images/blue_wallpaper.png", tier: 6 },
    "Yellow Wallpaper": { image: "images/yellow_wallpaper.png", tier: 6 },
    "Orange Wallpaper": { image: "images/orange_wallpaper.png", tier: 7 },
    "Carnival Wallpaper": { image: "images/carnival_wallpaper.png", tier: 8 },
    "Broccoli": { image: "images/broccoli.png", tier: 7 },
    "Carnival Pinwheel": { image: "images/carnival_pinwheel.png", tier: 9 },
    "Carnival Spikeball": { image: "images/carnival_spikeball.png", tier: 9 },
    "Golden Block": { image: "images/golden_block.png", tier: 10 },
    "Industrial Fan": { image: "images/industrial_fan.png", tier: 10 },
    "Ceiling Fan": { image: "images/ceiling_fan.png", tier: 11 },
    "Clouds": { image: "images/clouds.png", tier: 7 },
    "Checker Wallpaper": { image: "images/checker_wallpaper.png", tier: 7 },
    "Tomato": { image: "images/tomato.png", tier: 6 },
    "Egg": { image: "images/egg.png", tier: 21 },
    "Wheat": { image: "images/wheat.png", tier: 2 },
    "Dough": { image: "images/dough.png", tier: 22 },
    "Bread": { image: "images/bread.png", tier: 23 },
    "Stove": { image: "images/stove.png", tier: 10 },
    "Apron": { image: "images/apron.png", tier: 11 },
    "Spatula": { image: "images/spatula.png", tier: 11 },
    "Chef Hat": { image: "images/chef_hat.png", tier: 13 },
    "Carrot Block": { image: "images/carrot_block.png", tier: 8 },
    "Strawberry Block": { image: "images/strawberry_block.png", tier: 9 },
    "Polka Dot Block": { image: "images/polka_dot_block.png", tier: 10 },
    "Picket Fence": { image: "images/picket_fence.png", tier: 8 },
    "Traffic Barricade": { image: "images/traffic_barricade.png", tier: 11 },
    "Street Sign": { image: "images/street_sign.png", tier: 12 },
    "Open Sign": { image: "images/open_sign.png", tier: 13 },
    "Holographic Sign": { image: "images/holographic_sign.png", tier: 14 },
    "Straw Hat": { image: "images/straw_hat.png", tier: 12 },
    "Cheeseburger": { image: "images/cheeseburger.png", tier: 24 },
    "Wooden Background": { image: "images/wooden_background.png", tier: 6 },
    "Lattice Background": { image: "images/lattice_background.png", tier: 7 },
    "Beanbag": { image: "images/beanbag.png", tier: 18 },
    "Coral": { image: "images/coral.png", tier: 5 },
    "Seaweed": { image: "images/seaweed.png", tier: 3 },
    "Igneous Rock": { image: "images/igneous_rock.png", tier: 6 },
    "Laser Grid": { image: "images/laser_grid.png", tier: 9 },
    "Window": { image: "images/window.png", tier: 7 },
    "Glasses": { image: "images/glasses.png", tier: 8 },
    "Cyclopean Visor": { image: "images/cyclopean_visor.png", tier: 10 },
    "Matrix Visor": { image: "images/matrix_visor.png", tier: 11 },
    "Techno Visor": { image: "images/techno_visor.png", tier: 16 },
    "Computer Panel": { image: "images/computer_panel.png", tier: 15 },
    "Time-Space Rupture": { image: "images/time-space_rupture.png", tier: 16 },
    "Military Radio": { image: "images/military_radio.png", tier: 17 },
    "Deck Chair": { image: "images/deck_chair.png", tier: 18 },
    "Theater Seat": { image: "images/theater_seat.png", tier: 17 },
    "Couch": { image: "images/couch.png", tier: 17 },
    "Hay Chair": { image: "images/hay_chair.png", tier: 19 },
    "Flatscreen TV": { image: "images/flatscreen_tv.png", tier: 16 },
    "Chicken": { image: "images/chicken.png", tier: 20 },
    "Seagull": { image: "images/seagull.png", tier: 11 },
    "Asteroid": { image: "images/asteroid.png", tier: 12 },
    "Coffee Maker": { image: "images/coffee_maker.png", tier: 11 },
    "Microwave": { image: "images/microwave.png", tier: 18 },
    "Exclamation Sign": { image: "images/exclamation_sign.png", tier: 12 },
    "Warning Block": { image: "images/warning_block.png", tier: 11 },
    "Battery Block": { image: "images/battery_block.png", tier: 10 },
    "Steam Pipe": { image: "images/steam_pipe.png", tier: 19 },
    "Air Vent": { image: "images/air_vent.png", tier: 10 },
    "Steam Vent": { image: "images/steam_vent.png", tier: 20 },
    "Air Conditioner": { image: "images/air_conditioner.png", tier: 11 },
    "Table Lamp": { image: "images/table_lamp.png", tier: 9 },
    "Wooden Table": { image: "images/wooden_table.png", tier: 8 },
    "Chainlink Fence": { image: "images/chainlink_fence.png", tier: 9 },
    "Barbed Wire": { image: "images/barbed_wire.png", tier: 10 },
    "Bathtub": { image: "images/bathtub.png", tier: 9 },
    "Bathroom Mirror": { image: "images/bathroom_mirror.png", tier: 10 },
    "Funhouse Mirror": { image: "images/funhouse_mirror.png", tier: 11 },
    "Rubber Ducky": { image: "images/rubber_ducky.png", tier: 10 },
    "Plumbing": { image: "images/plumbing.png", tier: 10 },
    "Copper Block": { image: "images/copper_block.png", tier: 10 },
    "Purple Block": { image: "images/purple_block.png", tier: 6 },
    "Brown Block": { image: "images/brown_block.png", tier: 7 },
    "Blue Star Wallpaper": { image: "images/blue_star_wallpaper.png", tier: 7 },
    "Television": { image: "images/television.png", tier: 17 },
};
