const itemIndex = {
    "Dirt": "images/dirt.png",
    "Stone": "images/stone.png",
    "Stone Wall": "images/stone_wall.png",
    "Sand": "images/sand.png",
    "Lava": "images/lava.png",
    "Obsidian": "images/obsidian.png",
    "Marble": "images/marble.png",
    "Water": "images/water.png",
    "Grass": "images/grass.png",
    "Mud": "images/mud.png",
    "Soil": "images/soil.png",
    "Bush": "images/bush.png",
    "Tree": "images/tree.png",
    "Wood Block": "images/wood_block.png",
    "Rose": "images/rose.png",
    "Sunflower": "images/sunflower.png",
    "Cactus": "images/cactus.png",
    "Bricks": "images/bricks.png",
    "Well": "images/well.png",
    "Red Block": "images/red_block.png",
    "Green Block": "images/green_block.png",
    "Blue Block": "images/blue_block.png",
    "Yellow Block": "images/yellow_block.png",
    "Orange Block": "images/orange_block.png",
    "Forge": "images/forge.png",
    "Mushroom": "images/mushroom.png",
    "Glass Block": "images/glass_block.png",
    "Pinball Sproinger": "images/pinball_sproinger.png",
    "White Block": "images/white_block.png",
    "Black Block": "images/black_block.png",
    "Clay": "images/clay.png",
    "Toilet": "images/toilet.png",
    "Wooden Chair": "images/wooden_chair.png",
    "Bed": "images/bed.png",
};
